## STATBLE VERSION
# version: "3.8"
# services:
#   postgres:
#     build: ./db
#     env_file:
#       - path: ./.env
#         required: false
#     volumes:
#       - ./db:/docker-entrypoint-initdb.d
#     ports:
#       - "35432:5432"
#   app:
#     restart: on-failure
#     build: .
#     depends_on:
#       - postgres
#     env_file:
#       - path: ./.env
#         required: false
#     ports:
#       - "3000:3000"
#     command: npm run dev
#     volumes:
#       - .:/app/
#       - /app/nodde_modules

version: "3"
services:
  postgres: 
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=user123
      - POSTGRES_DB=db123
      - POSTGRES_PASSWORD=password123
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    image: monkeichow/express-psql-api
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_USER=user123
      - POSTGRES_DB=db123
      - POSTGRES_PASSWORD=password123
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
