# kind: Cluster
# apiVersion: kind.x-k8s.io/vlalpha4
# name: express-psql-kind
# nodes:
# - role: control-control-plane
#   kubeadmConfigPatches:
#   - |
#     kind: InitConfiguration
#     nodeRegistration:
#       node-labels: "ingress-ready=true"
#   extraPortMappings:
#   - containerPort: 80
#     hostPort: 80
#     protocol: TCP
#   - containerPort: 443
#     hostPort: 443
#     protocol: TCP
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: express-psql-app
#   labels:
#     name: express-psql-app
# spec:
#   containers:
#   - name: express-psql-app
#     image: express-psql-app
#     resources:
#       limits:
#         memory: "128Mi"
#         cpu: "500m"
#     ports:
#       - containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: express-psql-app
# spec:
#   selector:
#     app: express-psql-app
#   ports:
#   - port: 3000
#     targetPort: 3000

