# FROM node:16
# WORKDIR /app 
# COPY package*.json ./
# RUN npm i
# COPY . .
# CMD ["node","server.js"]

# FROM node:14.14.0-alpine
# WORKDIR /app
# COPY ./package.json ./
# RUN npm i
# COPY . .
# CMD ["npm", "run", "dev"]